// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Nim source code generator for nimiser.
// Takes parsed NimProc declarations and generates complete .nim files with:
//   - SPDX license header
//   - Module doc comment
//   - Type definitions (if any)
//   - Proc declarations with pragmas and stub bodies
//   - Helper templates for common patterns (e.g. wrapExportc)

use crate::abi::{NimPragma, NimProc, NimType};
use crate::manifest::Manifest;

/// Generate the complete .nim file content for the library.
/// Includes header, type section, proc declarations, and helper templates.
pub fn generate_nim_source(manifest: &Manifest, procs: &[NimProc]) -> String {
    let mut lines: Vec<String> = Vec::new();

    // --- File header ---
    lines.push("# SPDX-License-Identifier: PMPL-1.0-or-later".into());
    lines.push(format!(
        "# Generated by nimiser for library '{}'",
        manifest.project.name
    ));
    lines.push(format!("# Version: {}", manifest.project.version));
    if !manifest.project.description.is_empty() {
        lines.push(format!("# {}", manifest.project.description));
    }
    lines.push("#".into());
    lines.push("# DO NOT EDIT — regenerate with `nimiser generate`.".into());
    lines.push(String::new());

    // --- GC and compiler pragmas ---
    lines.push(format!(
        "# Compilation: nim {} --gc:{} -d:release --opt:{}",
        manifest.nim.backend, manifest.nim.gc, manifest.nim.opt_level,
    ));
    lines.push(String::new());

    // --- Helper template: wrapExportc ---
    // This template wraps a block of code with exportc + cdecl pragmas,
    // making it trivial to write C-exported functions with minimal boilerplate.
    lines.push("## Helper template: wrap a body in an exportc/cdecl proc.".into());
    lines.push("template wrapExportc*(name: untyped, body: untyped) =".into());
    lines.push("  proc name() {.exportc, cdecl.} =".into());
    lines.push("    body".into());
    lines.push(String::new());

    // --- Proc declarations ---
    for nim_proc in procs {
        // Doc comment.
        if let Some(ref doc) = nim_proc.doc {
            lines.push(format!("## {}", doc));
        }

        // Build the full proc with body.
        let signature = nim_proc.render_signature();
        lines.push(format!("{} =", signature));

        // Generate a stub body that returns a sensible default for the return type.
        let body = generate_stub_body(&nim_proc.return_type);
        lines.push(format!("  {}", body));

        lines.push(String::new());
    }

    lines.join("\n")
}

/// Generate a stub body for a proc based on its return type.
/// Returns a `result = <default>` statement or `discard` for void.
fn generate_stub_body(return_type: &Option<NimType>) -> String {
    match return_type {
        None => "discard".to_string(),
        Some(nim_type) => {
            let default_val = default_value_for_type(nim_type);
            format!("result = {}", default_val)
        }
    }
}

/// Produce a sensible default value for a Nim type.
/// Used in stub proc bodies so the generated code compiles immediately.
fn default_value_for_type(nim_type: &NimType) -> String {
    match nim_type {
        NimType::Primitive(name) => match name.as_str() {
            "cint" | "int" | "int8" | "int16" | "int32" | "int64" => "0".into(),
            "cuint" | "uint" | "uint8" | "uint16" | "uint32" | "uint64" => "0".into(),
            "cfloat" | "float" | "float32" => "0.0'f32".into(),
            "cdouble" | "float64" => "0.0".into(),
            "bool" => "false".into(),
            "char" => "'\\0'".into(),
            "cstring" => "cstring(\"\")".into(),
            "string" => "\"\"".into(),
            "pointer" => "nil".into(),
            _ => "default(typeof(result))".into(),
        },
        NimType::Ptr(_) => "nil".into(),
        NimType::Ref(_) => "nil".into(),
        NimType::Seq(_) => "@[]".into(),
        NimType::Array { size, element } => {
            let elem_default = default_value_for_type(element);
            // Nim array literal: [val, val, ...] or use default()
            if *size <= 8 {
                let elems: Vec<String> = (0..*size).map(|_| elem_default.clone()).collect();
                format!("[{}]", elems.join(", "))
            } else {
                "default(typeof(result))".into()
            }
        }
        NimType::Object { .. } | NimType::Alias(_) => "default(typeof(result))".into(),
    }
}

/// Generate a proc's full Nim representation including type annotations.
/// This is used for individual proc rendering in test contexts.
pub fn render_proc_with_body(nim_proc: &NimProc) -> String {
    let mut lines = Vec::new();
    if let Some(ref doc) = nim_proc.doc {
        lines.push(format!("## {}", doc));
    }
    lines.push(format!("{} =", nim_proc.render_signature()));
    lines.push(format!("  {}", generate_stub_body(&nim_proc.return_type)));
    lines.join("\n")
}

/// Check whether a proc has the exportc pragma.
pub fn is_exported(nim_proc: &NimProc) -> bool {
    nim_proc
        .pragmas
        .iter()
        .any(|p| matches!(p, NimPragma::Exportc | NimPragma::ExportcNamed(_)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::{NimParam, NimPragma};

    #[test]
    fn test_generate_stub_body_void() {
        assert_eq!(generate_stub_body(&None), "discard");
    }

    #[test]
    fn test_generate_stub_body_int() {
        let rt = Some(NimType::Primitive("cint".into()));
        assert_eq!(generate_stub_body(&rt), "result = 0");
    }

    #[test]
    fn test_generate_stub_body_float() {
        let rt = Some(NimType::Primitive("cdouble".into()));
        assert_eq!(generate_stub_body(&rt), "result = 0.0");
    }

    #[test]
    fn test_generate_stub_body_ptr() {
        let rt = Some(NimType::Ptr(Box::new(NimType::Primitive("cint".into()))));
        assert_eq!(generate_stub_body(&rt), "result = nil");
    }

    #[test]
    fn test_generate_stub_body_seq() {
        let rt = Some(NimType::Seq(Box::new(NimType::Primitive("int".into()))));
        assert_eq!(generate_stub_body(&rt), "result = @[]");
    }

    #[test]
    fn test_is_exported_true() {
        let p = NimProc {
            name: "test".into(),
            params: vec![],
            return_type: None,
            pragmas: vec![NimPragma::Exportc, NimPragma::Cdecl],
            doc: None,
        };
        assert!(is_exported(&p));
    }

    #[test]
    fn test_is_exported_false() {
        let p = NimProc {
            name: "test".into(),
            params: vec![],
            return_type: None,
            pragmas: vec![NimPragma::Inline],
            doc: None,
        };
        assert!(!is_exported(&p));
    }

    #[test]
    fn test_render_proc_with_body() {
        let p = NimProc {
            name: "add".into(),
            params: vec![
                NimParam {
                    name: "a".into(),
                    nim_type: NimType::Primitive("cint".into()),
                },
                NimParam {
                    name: "b".into(),
                    nim_type: NimType::Primitive("cint".into()),
                },
            ],
            return_type: Some(NimType::Primitive("cint".into())),
            pragmas: vec![NimPragma::Exportc, NimPragma::Cdecl],
            doc: Some("Add two integers.".into()),
        };
        let rendered = render_proc_with_body(&p);
        assert!(rendered.contains("## Add two integers."));
        assert!(rendered.contains("proc add(a: cint, b: cint): cint {.exportc, cdecl.} ="));
        assert!(rendered.contains("result = 0"));
    }
}
